### ISSUE TITLE
Intermittent 0 caplen alerts for output "alert_unixsock"

### ISSUE THREAD

**Issue by trunkfullofgoats** [snort3/snort3#340]
I'm reading alerts from a Unix Socket in Datagram mode via a python script and it seems every-so-often logs are coming through with a caplen of 0, as below (omitted the Alertpkt.pkt for brevity):

```
Alertmsg: b'"APP-DETECT SSH server detected on non-standard port"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
PcapPkthdr32:
  TsSec: 1706045390
  TsUsec: 190890
  Caplen: 0
  Len: 0
Dlthdr: 0
Nethdr: 0
Transhdr: 0
Data: 0
Val: 0
Gid: 1
Sid: 13586
Rev: 5
ClassId: 26
Priority: 3
EventId: 339
EventRef: 339
RefTsSec: 1706045390
RefTsUsec: 190890
```

From what I can tell by looking at "alert_unixsock.cc", in circumstances where a packet isn't available, caplen would be 0 and val would include the flag 0x1, but you can see from the above it does not (also the TS values are set above and that only happens when packet is available). So it seems the packet was not null but also (somehow) contained no data and yet was able to match to a rule.

Here's the arguments I ran with for the test (in the config all I've specified were the settings necessary for hyperscan, my HOME_NET and I enabled built-in rules):

```
/usr/local/test/bin/snort -c /run/test/ids/snort.lua --include-path /usr/local/test/etc/snort/ --plugin-path /run/test/ids/so_rules/ -i eth1 -A alert_unixsock -l /run/test/ids/ -R /run/test/ids/pulledpork-max-detect-so.rules -s 65535 -z 1 --daq afpacket --daq-dir /usr/local/test/lib/daq --daq-var fanout_type=hash
```

If needed I could provide the Python script I tested with.
