### ISSUE TITLE
Custom Rules Not Being Loaded in Snort 3.0.0 (Docker) ciscotalos/snort3

### ISSUE THREAD

**Issue by KaiZenSpace** [snort3/snort3#403]
Hello everyone,

I'm trying to get Snort 3 running in a Docker container with some custom rules, but I'm having trouble. Below is a summary of my setup and the problem I'm facing.

---

### Environment and Setup

- **Snort Version and Container:**  
Before compiling from Source, I am running with an old Docker image using Snort 3.0.0 (Build 267) which is also linked at snort.org/snort3. [[this Docker Hub repository](https://hub.docker.com/r/ciscotalos/snort3)](https://hub.docker.com/r/ciscotalos/snort3).  

  **Docker Container**
  ```
  snort3:
    image: my-snort3:latest
    container_name: snort3
    hostname: snort3#
    privileged: true
    user: snorty
    working_dir: /home/snorty
    stdin_open: true
    tty: true
    volumes:
      - /root/volumes/snort3/snort3/etc/snort:/home/snorty/snort3/etc/snort
      - /root/volumes/snort3/snort3/etc/rules:/home/snorty/snort3/etc/rules
      - /root/volumes/snort3/examples:/home/snorty/examples
      - /root/volumes/snort3/logs/alert_fast.txt:/var/log/snort/alert_fast.txt
    restart: unless-stopped
    command: bash
    network_mode: "host"
  ```

- **Directory Structure:**  
  The volumes are correctly mounted and point to the right files inside the container.

---

### Configuration

1. **snort.lua:**  
   Here it tells Snort where to look for rule files.
   ```lua
   -- Set the path where Snort looks for rule files
   rule_path = '/home/snorty/snort3/etc/rules'

   ips =
   {
       enable_builtin_rules = true,
       rules = { include = 'ips.rules' }
   }
   ```
   *Note:* I also tried using an absolute path (by commenting out `rule_path`), but it didn’t work.

2. **ips.rules:**  
   Located in `/home/snorty/snort3/etc/rules/` and contains:
   ```
   include 'tor_block.rules'
   include 'snort3-community.rules'
   ```

3. **tor_block.rules:**  
   For testing, I added a simple rule:
   ```
   alert icmp any any -> any any (msg:"ICMP Ping Detected"; sid:1000009; rev:1;)
   ```

4. **snort3-community.rules:**  
   This file has many rules and is the original free to use rule set that comes with the Docker image.

---

### Execution and Observed Behavior

- **Command to Run Snort:**  
  Snort is started in passive IDS mode with:
  ```
  snort -c /home/snorty/snort3/etc/snort/snort.lua -i eth0 -A alert_full
  ```

- **Expected Behavior:**  
  In addition to the built-in rules (500 rules), the custom rules (like the ICMP ping rule from tor_block.rules) should be loaded and active, making the total rule count at least 501.

- **Actual Behavior:**  
  The Snort output shows:
  ```
  Finished /home/snorty/snort3/etc/snort/snort.lua:
  Loading ips.rules:
  Finished ips.rules:
  --------------------------------------------------
  rule counts
         total rules loaded: 500 
              builtin rules: 500 <-----
              option chains: 500
              chain headers: 1
  --------------------------------------------------
  ```
  This means only the built-in rules are loaded—the files referenced in `ips.rules` (`tor_block.rules` and `snort3-community.rules`) are not integrated into the final rule set. Also, even when I comment out `enable_builtin_rules`, it has no effect.

---

### Summary of the Problem

- **Expectation:**  
  Including `ips.rules` (which in turn includes `tor_block.rules` and `snort3-community.rules`) should load my custom rules.

- **Observation:**  
  Despite correct volumes and path settings, only the internal rule set (500 rules) is loaded. Changes or errors in the custom rules (e.g., in `tor_block.rules`) do not affect the output or functionality. So it may well be that the rules are not loaded at all. Should it be logged when a custom ruleset is loaded? It only logs: 

´
  Finished /home/snorty/snort3/etc/snort/snort.lua:
  Loading ips.rules:
  Finished ips.rules:
´

---

I'm still trying to find a solution, while simultaneously hoping for help so that I can continue soon. I'll let you know when I've found a solution. Any suggestions or ideas would be greatly appreciated. Thanks in advance!

And if you have any resources you can recommend for getting started with Snort 3, please let me know!

Best regards,  
Kai
